services:
  fp-server:
    environment:
      - MY_SECRET=${MY_SECRET}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CORS_ORIGIN=${CORS_ORIGIN}
    build: .
    ports:
      - "80:3000"
