services:
  fp-server:
    environment:
      - MY_SECRET=${MY_SECRET}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
    build: .
    ports:
      - "3000:3000"
